In [ ]:
name = "Serenity"
print(name[1:5])
print(name[::-1])
print(name.upper())
print(len(name))

sentence = " hello world "
sentence = sentence.strip()
words = sentence.split()
print(words)
print("-".join(words))

s = "abcdefgh"
print(s[2:6])
print(s[::2])
print(s[1::3])

text = "Python is fun"
print(text.replace("fun", "great"))
print(text.count("i"))
print(text.startswith("Py"))

nums = [5, 3, 8, 1, 9, 2]
nums.sort()
print(nums)
nums.reverse()
print(nums[0])

items = ["a", "b", "c", "d", "e"]
items.insert(2, "z")
items.pop()
print(items)
print(items.index("z"))

a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(c)
print(c[2:5])
print(sum(c))

nums = [1, 2, 3, 4, 5, 6, 7, 8]
result = [x**2 for x in nums if x % 2 == 0]
print(result)

coords = (3, 7)
x, y = coords
print('x =', x)
print('y =', y)
print(type(coords))

a, *b, c = (1, 2, 3, 4, 5)
print(a)
print(b)
print(c)

records = [(1, "Ada"), (2, "Kimi"), (3, "Sophie")]
for num, name in records:
    print(num, "->", name)

profile = {"name": "Cedric", "age": 20, "grade": "B"}
profile["age"] = 21
profile["city"] = "Lagos"
print(profile)
print(profile.get("grade"))

scores = {"Math": 85, "CS": 92, "English": 78}
print(scores.keys())
print(scores.values())
print(max(scores, key=scores.get))

d = {"a": 1, "b": 2, "c": 3}
d.pop("b")
for key, val in d.items():
    print(key, ":", val)

text = "mississippi"
freq = {}
for ch in text:
    freq[ch] = freq.get(ch, 0) + 1
print(freq)

a = {"x": 1, "y": 2}
b = {"y": 10, "z": 3}
merged = {**a, **b}
print(merged)

s1 = {1, 2, 3, 4, 5}
s2 = {3, 4, 5, 6, 7}
print(s1 & s2)
print(s1 | s2)
print(s1 - s2)

names = ["Ada", "Kimi", "Ada", "Sophie", "Kimi", "Ada"]
unique = set(names)
print(unique)
print(len(unique))

score = 74
if score >= 90:
    print('A')
elif score >= 75:
    print('B')
elif score >= 60:
    print('C')
else:
    print('F')

x = 15
result = 'big' if x > 10 else 'small'
print(result)
print('odd' if x % 2 != 0 else 'even')

total = 0
for i in range(1, 11):
    if i % 2 == 0:
        continue
    total += i
print(total)

n = 1
while n < 100:
    n *= 3
    if n > 50:
        break
print(n)

fruits = ["mango", "grape", "apple"]
for i, fruit in enumerate(fruits):
    print(i, fruit)

a = [1, 2, 3]
b = ["x", "y", "z"]
for num, letter in zip(a, b):
    print(num, letter)

def add(a, b=10):
    return a + b
print(add(5))
print(add(5, 20))
print(add(b=3, a=7))

def describe(*args, **kwargs):
    print(args)
    print(kwargs)
describe(1, 2, 3, name="Ada", age=19)

double = lambda x: x * 2
add = lambda x, y: x + y
nums = [1, 2, 3, 4, 5]
result = list(map(double, nums))
print(result)
print(add(3, 7))

def factorial(n):
    if n <= 1:
        return 1
    return n * factorial(n - 1)
print(factorial(5))
print(factorial(7))

def fib(n):
    if n <= 1:
        return n
    return fib(n-1) + fib(n-2)
for i in range(8):
    print(fib(i), end=' ')
print()

name = 'Kimi'
score = 91.5
print(f'Name: {name}, Score: {score:.1f}')
print(f"{'Title':>20}")
print(f'{42:05d}')

items = ["pen", "book", "bag"]
for i, item in enumerate(items, start=1):
    print(f"{i}. {item.capitalize()}")

students = [
{"name": "Ada", "grade": 88},
{"name": "Sophie", "grade": 95},
{"name": "Esther", "grade": 76}
]
top = max(students, key=lambda s: -s["grade"])
print(top["name"])

matrix = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
flat = [n for row in matrix for n in row]
print(flat)
print(matrix[2][1])

graph = {
"A": ["B", "C"],
"B": ["A", "D"],
"C": ["A"],
"D": ["B"]
}
print(graph["B"])
print(len(graph["A"]))

def divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return 'Cannot divide by zero'
print(divide(10, 2))
print(divide(5, 0))

values = ["10", "abc", "30", "xyz", "50"]
total = 0
for v in values:
    try:
        total += int(v)
    except ValueError:
        pass
print(total)

paragraph = "the quick brown fox"
titled = paragraph.title()
words = titled.split()
words.sort()
print(" ".join(words))

s = "racecar"
is_palindrome = s == s[::-1]
print(is_palindrome)
s2 = "hello"
print(s2 == s2[::-1])

def count_up(limit):
    n = 0
    while n < limit:
        yield n
        n += 1
for val in count_up(5):
    print(val, end=' ')
print()


squares = (x**2 for x in range(1, 8))
for s in squares:
    print(s, end=' ')
print()

class Animal:
    def __init__(self, name, sound):
        self.name = name
        self.sound = sound
    def speak(self):
        return f'{self.name} says {self.sound}'
dog = Animal('Dog', 'woof')
print(dog.speak())

class Counter:
    def __init__(self):
        self.count = 0
    def increment(self):
        self.count += 1
    def decrement(self):
        self.count -= 1
    def reset(self):
        self.count = 0
c = Counter()
c.increment()
c.increment()
c.increment()
print(c.count)
c.reset()
print(c.count)
c.decrement()
print(c.count)

data = [(3, "banana"), (1, "apple"), (2, "mango")]
data.sort(key=lambda x: x[0])
print(data)
names = ["Zara", "Ada", "Kimi"]
print(sorted(names))

def process(nums):
    result = {}
    for n in nums:
        key = 'even' if n % 2 == 0 else 'odd'
        result.setdefault(key, []).append(n)
        return result
data = [1, 2, 3, 4, 5, 6, 7, 8]
print(process(data))

In [2]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
b = np.zeros((2, 4), dtype=int)
c = np.arange(1, 13).reshape(3, 4)
print(a.shape)
print(b)
print(c[1, 2])
print(c[-1, -1])






(3, 3)
[[0 0 0 0]
 [0 0 0 0]]
7
12
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[ 3  8 13 18 23]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[16 17 18 19 20 21 22 23 24 25]


In [6]:
import numpy as np
m = np.arange(1, 26).reshape(5, 5)
print(m[1:4, 1:4])
print(m[:, 2])
print(m[::2, ::2])
print(m[m > 15])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[ 3  8 13 18 23]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[16 17 18 19 20 21 22 23 24 25]


In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a + b)
print(a * b)
print(np.dot(a, b))
print(np.sum(a))
print(np.mean(b))
print(np.sqrt(a.astype(float)))

[11 22 33 44]
[ 10  40  90 160]
300
10
25.0
[1.         1.41421356 1.73205081 2.        ]


In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([7, 8, 9, 10, 11, 12])
stacked = np.vstack([a.reshape(2, 3), b.reshape(2, 3)])
flat = stacked.flatten()
print(stacked)
print(stacked.T)
print(flat[::2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[ 1  3  5  7  9 11]


In [11]:
data = {
"name": ["Ada", "Kimi", "Sophie", "Esther"],
"score": [88, 95, 72, 81],
"grade": ["B", "A", "C", "B"]
}
df = pd.DataFrame(data)
print(df[df["score"] > 80])
print(df["score"].mean())
print(df.sort_values("score", ascending=False))

     name  score grade
0     Ada     88     B
1    Kimi     95     A
3  Esther     81     B
84.0
     name  score grade
1    Kimi     95     A
0     Ada     88     B
3  Esther     81     B
2  Sophie     72     C


In [12]:
df = pd.DataFrame({
"dept": ["CS", "CS", "Math", "Math", "CS"],
"name": ["Ada", "Kimi", "Sophie", "Esther", "Cedric"],
"score": [88, 95, 72, 81, 76]
})
grouped = df.groupby("dept")["score"]
print(grouped.mean())
print(grouped.max())
print(df.groupby("dept").size())

dept
CS      86.333333
Math    76.500000
Name: score, dtype: float64
dept
CS      95
Math    81
Name: score, dtype: int64
dept
CS      3
Math    2
dtype: int64


In [14]:
class Counter:
    count = 0

    def __init__(self):
        Counter.count += 1

a = Counter()
b = Counter()
c = Counter()
print(Counter.count)
print(a.count)

print(b.count)

3
3
3
