In [2]:
import numpy as np

In [3]:
print(np.__version__);

2.4.3


In [ ]:
arr = np.array([101, 201, 301, 401, 501]);

print(arr);

print(type(arr));

[101 201 301 401 501]
<class 'numpy.ndarray'>


In [ ]:
name_list = ['Angel', 'Shemi', 'Marvel', 'Linda'];

age_tuple = (41, 32, 21, 19);

grade_dictionary = {
    'CSC102' :89,
    'MTH102' : 77,
    'CHM102': 69,
    'GST102': 99
}

arr_name_list = np.array(name_list);
arr_age_tuple = np.array(age_tuple);
arr_grade_dict = np.array(grade_dictionary);

print(arr_name_list);
print(arr_age_tuple);
print(arr_grade_dict);
print(type(arr_grade_dict));

['Angel' 'Shemi' 'Marvel' 'Linda']
[41 32 21 19]
{'CSC102': 89, 'MTH102': 77, 'CHM102': 69, 'GST102': 99}
<class 'numpy.ndarray'>


In [7]:
# 0 Dimensional Arrays

class_num = int(input("How many students are in the COS102 class?"));
class_arr = np.array(class_num);

if class_arr == 1:
    print("There is only", class_arr, "student in CSC102");
else:
    print("There are", class_arr, "students in CSC102");

print(class_arr);

There are 5 students in CSC102
5


In [ ]:
# 1 Dimensional Arraus

arr = np.array([1, 2, 3, 4, 5]);

print(arr);
print(arr.shape) #returns (5, _), meaning 1D array with 5 elements


[1 2 3 4 5]
(5,)


In [ ]:
# 2 Dimensional Arrays
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print(arr);
print(arr.shape); # returns (2,3) meaning 2 rows, 3 cols

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
arr = np.array(
    [[[1,2,3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1,2 ,3], [4,5,6]]]
);

print(arr);
print(arr.shape);

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)


In [ ]:
a = np.array(42)
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 2, 3, 4, 5])

#check dimensions with .ndim
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
3
2
1


In [13]:
#Higher dimensional arrays

arr = np.array([1,2,3,4], ndmin=21); #arr has 21 dimensions now

print(arr);
print("a has ", arr.ndim, 'dimensions')
arr.shape

[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]
a has  21 dimensions


(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)