In [2]:
import numpy as np

In [3]:
print(np.__version__);

2.4.3


In [ ]:
arr = np.array([101, 201, 301, 401, 501]);

print(arr);

print(type(arr));

[101 201 301 401 501]
<class 'numpy.ndarray'>


In [ ]:
name_list = ['Angel', 'Shemi', 'Marvel', 'Linda'];

age_tuple = (41, 32, 21, 19);

grade_dictionary = {
    'CSC102' :89,
    'MTH102' : 77,
    'CHM102': 69,
    'GST102': 99
}

arr_name_list = np.array(name_list);
arr_age_tuple = np.array(age_tuple);
arr_grade_dict = np.array(grade_dictionary);

print(arr_name_list);
print(arr_age_tuple);
print(arr_grade_dict);
print(type(arr_grade_dict));

['Angel' 'Shemi' 'Marvel' 'Linda']
[41 32 21 19]
{'CSC102': 89, 'MTH102': 77, 'CHM102': 69, 'GST102': 99}
<class 'numpy.ndarray'>


In [7]:
# 0 Dimensional Arrays

class_num = int(input("How many students are in the COS102 class?"));
class_arr = np.array(class_num);

if class_arr == 1:
    print("There is only", class_arr, "student in CSC102");
else:
    print("There are", class_arr, "students in CSC102");

print(class_arr);

There are 5 students in CSC102
5


In [ ]:
# 1 Dimensional Arraus

arr = np.array([1, 2, 3, 4, 5]);

print(arr);
print(arr.shape) #returns (5, _), meaning 1D array with 5 elements


[1 2 3 4 5]
(5,)


In [ ]:
# 2 Dimensional Arrays
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print(arr);
print(arr.shape); # returns (2,3) meaning 2 rows, 3 cols

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
arr = np.array(
    [[[1,2,3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1,2 ,3], [4,5,6]]]
);

print(arr);
print(arr.shape);

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)


In [ ]:
a = np.array(42)
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 2, 3, 4, 5])

#check dimensions with .ndim
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
3
2
1


In [13]:
#Higher dimensional arrays

arr = np.array([1,2,3,4], ndmin=21); #arr has 21 dimensions now

print(arr);
print("a has ", arr.ndim, 'dimensions')
arr.shape

[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]
a has  21 dimensions


(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)

In [3]:
arr = np.array([1,2,3,4]);

print(arr[1]);

2


In [5]:
arr = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]]
);

print("The 5th element on the 2nd row is" , arr[1,4]);

The 5th element on the 2nd row is 10


In [ ]:
arr = np.array([
        [
            [1,2,3,4,5],
            [4,5,6,0,6]
        ],
        [
            [7,8,9,8,5],
            [10,11,12,6,9]
        ]
    ]
);

print(arr)
print(arr.shape)
print(arr[0,1,4]);

[[[ 1  2  3  4  5]
  [ 4  5  6  0  6]]

 [[ 7  8  9  8  5]
  [10 11 12  6  9]]]
(2, 2, 5)
6


In [11]:
arr = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ]
);

print("Last element from first dimension is ", arr[0,-1]);
print("Last element from second dimension is ", arr[1,-1]);


Last element from first dimension is  5
Last element from second dimension is  10


In [12]:
arr = np.array(
    [1,2,3,4,5,6,7]
);

print(arr[1:5]);

print(arr[4:]);

print(arr[:4]);

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [13]:
#lets iter on some arrays

arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
);

for x in arr:
    for y in x:
        print(y,x);

1 [1 2 3]
2 [1 2 3]
3 [1 2 3]
4 [4 5 6]
5 [4 5 6]
6 [4 5 6]


In [14]:
#iter over a 3d array

arr = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [7,8,9],
            [10,11,12]
        ]
    ] 
);

for x in arr:
    for y in x:
        for z in y:
            print(z,y,x);

1 [1 2 3] [[1 2 3]
 [4 5 6]]
2 [1 2 3] [[1 2 3]
 [4 5 6]]
3 [1 2 3] [[1 2 3]
 [4 5 6]]
4 [4 5 6] [[1 2 3]
 [4 5 6]]
5 [4 5 6] [[1 2 3]
 [4 5 6]]
6 [4 5 6] [[1 2 3]
 [4 5 6]]
7 [7 8 9] [[ 7  8  9]
 [10 11 12]]
8 [7 8 9] [[ 7  8  9]
 [10 11 12]]
9 [7 8 9] [[ 7  8  9]
 [10 11 12]]
10 [10 11 12] [[ 7  8  9]
 [10 11 12]]
11 [10 11 12] [[ 7  8  9]
 [10 11 12]]
12 [10 11 12] [[ 7  8  9]
 [10 11 12]]


In [15]:
#alternatively just use nditer to iterate

for z in np.nditer(arr):
    print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [18]:
arr1 = np.array([1,2,3]);

arr2 = np.array([4,5,6]);

arr = np.concatenate((arr1, arr2));

print(arr);

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1,2,3,4,5,6]);

# splits arr into even 6 parts, each element is its own array

newarr = np.array_split(arr,6);

print(newarr);

#splits into 3 arrays containing pairs
newarr = np.array_split(arr, 3);

print(newarr);
print(newarr[1]);

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [25]:
arr = np.array([1,2,3,4,5,6,7]);

newarr = np.array_split(arr, 3);

# array_split always finds a way to divide evenly
# if you try normally splitting and it cant divide evenly, its gonna crash

newarr2 = np.split(arr, 3);

print(newarr2);

print(newarr);

ValueError: array split does not result in an equal division

In [ ]:
#lets split a 2d array

arr = np.array(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10]
    ]
)